//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealership_BD2._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public int Customer_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public string OrderDate { get; set; }
        public int Amount { get; set; }
    
        public virtual Customers Customers { private get; set; }
        public virtual Vehicles Vehicles { private get; set; }
    }
}
